version: '3.4'
services:
  dns-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - './conf/named.conf.local:/etc/bind/named.conf.local'
      - './conf/named.conf.options:/etc/bind/named.conf.options'
